package contracts

import (
	"encoding/json"
	"strings"
	"testing"

	"github.com/tamnguyendinh/anvien/internal/semantic"
)

func TestWebUIContractManifestUsesGoRuntimeConstants(t *testing.T) {
	manifest := WebUIContract()

	if !contains(manifest.Graph.NodeLabels, "Project") || !contains(manifest.Graph.NodeLabels, "Tool") || !contains(manifest.Graph.NodeLabels, "ResolutionGap") {
		t.Fatalf("node labels missing Go ScopeIR labels: %#v", manifest.Graph.NodeLabels)
	}
	if !contains(manifest.Graph.LadybugDBNodeTables, "Package") || !contains(manifest.Graph.LadybugDBNodeTables, "ResolutionGap") {
		t.Fatalf("LadybugDB node tables missing Package: %#v", manifest.Graph.LadybugDBNodeTables)
	}
	if !contains(manifest.Graph.LadybugDBRelationshipTypes, "OVERRIDES") || !contains(manifest.Graph.LadybugDBRelationshipTypes, "HAS_RESOLUTION_GAP") {
		t.Fatalf("LadybugDB relationship types missing legacy OVERRIDES: %#v", manifest.Graph.LadybugDBRelationshipTypes)
	}
	if !contains(manifest.Graph.GraphRelationshipTypes, "DECORATES") || !contains(manifest.Graph.GraphRelationshipTypes, "HAS_RESOLUTION_GAP") {
		t.Fatalf("graph relationship types missing DECORATES: %#v", manifest.Graph.GraphRelationshipTypes)
	}
	if manifest.Graph.RelationshipTableName != "CodeRelation" || manifest.Graph.EmbeddingTableName != "CodeEmbedding" {
		t.Fatalf("unexpected table names: %#v", manifest.Graph)
	}
	if len(manifest.Graph.RelationshipDisplayPolicy) != len(manifest.Graph.GraphRelationshipTypes) {
		t.Fatalf("relationship display policy count mismatch: %#v", manifest.Graph.RelationshipDisplayPolicy)
	}
	if !contains(manifest.Graph.GraphHealthDiagnosticClassifications, "builtin") ||
		!contains(manifest.Graph.GraphHealthDiagnosticActionabilities, "analyzer_gap") ||
		!contains(manifest.Graph.GraphHealthReportTriageDimensions, "diagnostic") {
		t.Fatalf("graph health contract metadata missing: %#v", manifest.Graph)
	}
	if !contains(manifest.Graph.AppLayers, "backend") || !contains(manifest.Graph.AppLayers, "api") ||
		!contains(manifest.Graph.AppLayers, "frontend") || !contains(manifest.Graph.AppLayers, "frontend_api_client") {
		t.Fatalf("app layer contract metadata missing: %#v", manifest.Graph.AppLayers)
	}
	if manifest.Graph.SemanticSchemaVersion == "" || !contains(manifest.Graph.SemanticStatusValues, "stale_incomplete") {
		t.Fatalf("semantic status contract metadata missing: %#v", manifest.Graph)
	}
	if term := termDefinition(manifest.Graph.SemanticTerms, "resolution_gap"); term.WebLabel != "Resolution Gap" {
		t.Fatalf("resolution gap term = %#v", term)
	}
	if label := termDefinition(manifest.Graph.AppLayerLabels, "api"); label.DisplayLabel != "API Layer" {
		t.Fatalf("api app layer label = %#v", label)
	}
	if !contains(manifest.Graph.FunctionalAreas, "resolution") || !contains(manifest.Graph.FunctionalAreas, "graph_health") {
		t.Fatalf("functional area contract metadata missing: %#v", manifest.Graph.FunctionalAreas)
	}
	if label := termDefinition(manifest.Graph.FunctionalAreaLabels, "resolution"); label.DisplayLabel != "Resolution" {
		t.Fatalf("resolution functional area label = %#v", label)
	}
	if policy := relationshipPolicy(manifest, "INHERITS"); policy.SemanticGroup != "normalized-heritage" {
		t.Fatalf("INHERITS policy = %#v", policy)
	}
	if policy := relationshipPolicy(manifest, "HAS_RESOLUTION_GAP"); policy.SemanticGroup != "resolution-health" {
		t.Fatalf("HAS_RESOLUTION_GAP policy = %#v", policy)
	}
	if len(manifest.Languages.GraphCoverage) != len(manifest.Languages.CodeLanguages) {
		t.Fatalf("language graph coverage count mismatch: %#v", manifest.Languages.GraphCoverage)
	}
	if coverage := findLanguageCoverage(manifest, "cobol"); coverage.ExtractorStatus != "dedicated-analyzer-phase" {
		t.Fatalf("COBOL coverage = %#v", coverage)
	}
	for _, coverage := range manifest.Languages.GraphCoverage {
		requireExplicitLanguageCoverage(t, coverage)
	}

	raw, err := WebUIContractJSON()
	if err != nil {
		t.Fatalf("WebUIContractJSON() error = %v", err)
	}
	var decoded WebUIContractManifest
	if err := json.Unmarshal(raw, &decoded); err != nil {
		t.Fatalf("generated manifest is not JSON: %v", err)
	}
}

func TestWebUIContractTypeScriptIsBrowserGeneratedGlue(t *testing.T) {
	source, err := WebUIContractTypeScript()
	if err != nil {
		t.Fatalf("WebUIContractTypeScript() error = %v", err)
	}

	for _, want := range []string{
		"Code generated by `go run ./cmd/generate-web-contracts`",
		"export const NODE_TABLES",
		"export const RELATIONSHIP_DISPLAY_POLICY",
		"export const LANGUAGE_GRAPH_COVERAGE",
		"export interface GraphNode",
		"export const GRAPH_HEALTH_TOPOLOGY_STATUSES",
		"export const GRAPH_HEALTH_DIAGNOSTIC_CLASSIFICATIONS",
		"export type GraphHealthDiagnosticActionability",
		"export interface GraphHealthComponentSummary",
		"export interface GraphHealthSummary",
		"export const APP_LAYERS",
		"export const APP_LAYER_LABELS",
		"export const SEMANTIC_TERMS",
		"export type SemanticStatusValue",
		"export interface GraphSemanticStatus",
		"export const FUNCTIONAL_AREAS",
		"export type FunctionalArea",
		"export type AppLayer",
		"appLayer?: AppLayer",
		"functionalArea?: FunctionalArea",
		"semanticStatus?: GraphSemanticStatus",
		"diagnosticClassificationCounts: Partial<Record<GraphHealthDiagnosticClassification, number>>",
		"triageDimension: GraphHealthReportTriageDimension",
		"largestDetachedComponents?: GraphHealthComponentSummary[]",
		"graphHealth?: GraphHealthNodeMetadata",
		"export interface SessionStatusResponse",
		"export const getSyntaxLanguageFromFilename",
	} {
		if !strings.Contains(source, want) {
			t.Fatalf("generated TypeScript missing %q", want)
		}
	}
	if strings.Contains(source, "anvien-shared") || strings.Contains(source, "node:") {
		t.Fatalf("generated TypeScript must stay browser-only glue:\n%s", source)
	}
}

func relationshipPolicy(manifest WebUIContractManifest, relType string) RelationshipDisplayPolicy {
	for _, policy := range manifest.Graph.RelationshipDisplayPolicy {
		if policy.Type == relType {
			return policy
		}
	}
	return RelationshipDisplayPolicy{}
}

func findLanguageCoverage(manifest WebUIContractManifest, language string) LanguageGraphCoverage {
	for _, coverage := range manifest.Languages.GraphCoverage {
		if coverage.Language == language {
			return coverage
		}
	}
	return LanguageGraphCoverage{}
}

func termDefinition(terms []semantic.TermDefinition, key string) semantic.TermDefinition {
	for _, term := range terms {
		if term.Key == key {
			return term
		}
	}
	return semantic.TermDefinition{}
}

func requireExplicitLanguageCoverage(t *testing.T, coverage LanguageGraphCoverage) {
	t.Helper()
	if coverage.Language == "" || coverage.ExtractorStatus == "" {
		t.Fatalf("coverage identity is incomplete: %#v", coverage)
	}
	if len(coverage.FactFamilies) == 0 {
		t.Fatalf("%s coverage has no explicit fact families: %#v", coverage.Language, coverage)
	}
	if len(coverage.SourceFactFamilies) != len(coverage.FactFamilies) {
		t.Fatalf("%s source fact family names are not derived from explicit fact coverage: %#v", coverage.Language, coverage)
	}
	byFamily := map[string]LanguageFactCoverage{}
	for index, fact := range coverage.FactFamilies {
		if fact.Family == "" || fact.Status == "" || fact.Evidence == "" {
			t.Fatalf("%s fact family %d is incomplete: %#v", coverage.Language, index, fact)
		}
		if !allowedFactStatus(fact.Status) {
			t.Fatalf("%s/%s has unsupported status %q", coverage.Language, fact.Family, fact.Status)
		}
		if coverage.SourceFactFamilies[index] != fact.Family {
			t.Fatalf("%s source family %d = %q, want %q", coverage.Language, index, coverage.SourceFactFamilies[index], fact.Family)
		}
		byFamily[fact.Family] = fact
	}
	if coverage.ExtractorStatus == "scopeir-provider-backed" {
		if contains(coverage.SourceFactFamilies, "heritage-where-language-supports-it") {
			t.Fatalf("%s still uses generic heritage coverage marker: %#v", coverage.Language, coverage.SourceFactFamilies)
		}
		for _, family := range []string{"definitions", "imports", "calls", "accesses", "type-references", "members", "heritage"} {
			if _, ok := byFamily[family]; !ok {
				t.Fatalf("%s missing explicit provider fact family %q in %#v", coverage.Language, family, coverage.FactFamilies)
			}
		}
		if len(coverage.SupportedNodeLabels) == 0 || len(coverage.SupportedRelationshipTypes) == 0 {
			t.Fatalf("%s provider-backed coverage lacks node/relationship inventory: %#v", coverage.Language, coverage)
		}
		if coverage.ProviderParityProofLevel == "" || coverage.DefaultRegressionGate == "" {
			t.Fatalf("%s provider-backed coverage lacks proof/gate metadata: %#v", coverage.Language, coverage)
		}
	}
}

func allowedFactStatus(status string) bool {
	switch status {
	case "resolved-graph-output",
		"extracted-but-unresolved-external",
		"extraction-only-inventory",
		"not-applicable-by-language-semantics",
		"scanned-not-extracted",
		"dedicated-analyzer-phase":
		return true
	default:
		return false
	}
}

func contains(values []string, want string) bool {
	for _, value := range values {
		if value == want {
			return true
		}
	}
	return false
}
