package contracts

import (
	"encoding/json"
	"strings"
	"testing"
)

func TestWebUIContractManifestUsesGoRuntimeConstants(t *testing.T) {
	manifest := WebUIContract()

	if !contains(manifest.Graph.NodeLabels, "Project") || !contains(manifest.Graph.NodeLabels, "Tool") {
		t.Fatalf("node labels missing Go ScopeIR labels: %#v", manifest.Graph.NodeLabels)
	}
	if !contains(manifest.Graph.LadybugDBNodeTables, "Package") {
		t.Fatalf("LadybugDB node tables missing Package: %#v", manifest.Graph.LadybugDBNodeTables)
	}
	if !contains(manifest.Graph.LadybugDBRelationshipTypes, "OVERRIDES") {
		t.Fatalf("LadybugDB relationship types missing legacy OVERRIDES: %#v", manifest.Graph.LadybugDBRelationshipTypes)
	}
	if !contains(manifest.Graph.GraphRelationshipTypes, "DECORATES") {
		t.Fatalf("graph relationship types missing DECORATES: %#v", manifest.Graph.GraphRelationshipTypes)
	}
	if manifest.Graph.RelationshipTableName != "CodeRelation" || manifest.Graph.EmbeddingTableName != "CodeEmbedding" {
		t.Fatalf("unexpected table names: %#v", manifest.Graph)
	}
	if len(manifest.Graph.RelationshipDisplayPolicy) != len(manifest.Graph.GraphRelationshipTypes) {
		t.Fatalf("relationship display policy count mismatch: %#v", manifest.Graph.RelationshipDisplayPolicy)
	}
	if policy := relationshipPolicy(manifest, "INHERITS"); policy.SemanticGroup != "normalized-heritage" {
		t.Fatalf("INHERITS policy = %#v", policy)
	}
	if len(manifest.Languages.GraphCoverage) != len(manifest.Languages.CodeLanguages) {
		t.Fatalf("language graph coverage count mismatch: %#v", manifest.Languages.GraphCoverage)
	}
	if coverage := languageCoverage(manifest, "cobol"); coverage.ExtractorStatus != "dedicated-analyzer-phase" {
		t.Fatalf("COBOL coverage = %#v", coverage)
	}

	raw, err := WebUIContractJSON()
	if err != nil {
		t.Fatalf("WebUIContractJSON() error = %v", err)
	}
	var decoded WebUIContractManifest
	if err := json.Unmarshal(raw, &decoded); err != nil {
		t.Fatalf("generated manifest is not JSON: %v", err)
	}
}

func TestWebUIContractTypeScriptIsBrowserGeneratedGlue(t *testing.T) {
	source, err := WebUIContractTypeScript()
	if err != nil {
		t.Fatalf("WebUIContractTypeScript() error = %v", err)
	}

	for _, want := range []string{
		"Code generated by `go run ./cmd/generate-web-contracts`",
		"export const NODE_TABLES",
		"export const RELATIONSHIP_DISPLAY_POLICY",
		"export const LANGUAGE_GRAPH_COVERAGE",
		"export interface GraphNode",
		"export interface SessionStatusResponse",
		"export const getSyntaxLanguageFromFilename",
	} {
		if !strings.Contains(source, want) {
			t.Fatalf("generated TypeScript missing %q", want)
		}
	}
	if strings.Contains(source, "avmatrix-shared") || strings.Contains(source, "node:") {
		t.Fatalf("generated TypeScript must stay browser-only glue:\n%s", source)
	}
}

func relationshipPolicy(manifest WebUIContractManifest, relType string) RelationshipDisplayPolicy {
	for _, policy := range manifest.Graph.RelationshipDisplayPolicy {
		if policy.Type == relType {
			return policy
		}
	}
	return RelationshipDisplayPolicy{}
}

func languageCoverage(manifest WebUIContractManifest, language string) LanguageGraphCoverage {
	for _, coverage := range manifest.Languages.GraphCoverage {
		if coverage.Language == language {
			return coverage
		}
	}
	return LanguageGraphCoverage{}
}

func contains(values []string, want string) bool {
	for _, value := range values {
		if value == want {
			return true
		}
	}
	return false
}
