package contracts

import (
	"encoding/json"
	"strings"
	"testing"
)

func TestWebUIContractManifestUsesGoRuntimeConstants(t *testing.T) {
	manifest := WebUIContract()

	if !contains(manifest.Graph.NodeLabels, "Project") || !contains(manifest.Graph.NodeLabels, "Tool") {
		t.Fatalf("node labels missing Go ScopeIR labels: %#v", manifest.Graph.NodeLabels)
	}
	if !contains(manifest.Graph.LadybugDBNodeTables, "Package") {
		t.Fatalf("LadybugDB node tables missing Package: %#v", manifest.Graph.LadybugDBNodeTables)
	}
	if !contains(manifest.Graph.LadybugDBRelationshipTypes, "OVERRIDES") {
		t.Fatalf("LadybugDB relationship types missing legacy OVERRIDES: %#v", manifest.Graph.LadybugDBRelationshipTypes)
	}
	if !contains(manifest.Graph.GraphRelationshipTypes, "DECORATES") {
		t.Fatalf("graph relationship types missing DECORATES: %#v", manifest.Graph.GraphRelationshipTypes)
	}
	if manifest.Graph.RelationshipTableName != "CodeRelation" || manifest.Graph.EmbeddingTableName != "CodeEmbedding" {
		t.Fatalf("unexpected table names: %#v", manifest.Graph)
	}

	raw, err := WebUIContractJSON()
	if err != nil {
		t.Fatalf("WebUIContractJSON() error = %v", err)
	}
	var decoded WebUIContractManifest
	if err := json.Unmarshal(raw, &decoded); err != nil {
		t.Fatalf("generated manifest is not JSON: %v", err)
	}
}

func TestWebUIContractTypeScriptIsBrowserGeneratedGlue(t *testing.T) {
	source, err := WebUIContractTypeScript()
	if err != nil {
		t.Fatalf("WebUIContractTypeScript() error = %v", err)
	}

	for _, want := range []string{
		"Code generated by `go run ./cmd/generate-web-contracts`",
		"export const NODE_TABLES",
		"export interface GraphNode",
		"export interface SessionStatusResponse",
		"export const getSyntaxLanguageFromFilename",
	} {
		if !strings.Contains(source, want) {
			t.Fatalf("generated TypeScript missing %q", want)
		}
	}
	if strings.Contains(source, "avmatrix-shared") || strings.Contains(source, "node:") {
		t.Fatalf("generated TypeScript must stay browser-only glue:\n%s", source)
	}
}

func contains(values []string, want string) bool {
	for _, value := range values {
		if value == want {
			return true
		}
	}
	return false
}
